SCC <- readRDS("Source_Classification_Code.rds")
NEI <- readRDS("summarySCC_PM25.rds")
NEI$Emissions <- as.numeric(NEI$Emissions)
NEI <- transform(NEI, year = factor(year))
tmi <- tapply(NEI$Emissions, NEI$year, sum)
barplot(tmi,xlab="Years", ylab="Total Emissions",main="Total Emissions Over Years")